stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
      - apt-get update --yes
      - apt-get install --yes cmake clang clang-dev
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
      - apt-get update --yes
      - apt-get install --yes cmake clang clang-dev
  script:
    - cargo build --verbose
    - cargo test --verbose
