stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
      - echo "deb http://deb.debian.org/debian experimental main" >> /etc/apt/sources.list
      - echo "deb http://security.debian.org testing main" >> /etc/apt/sources.list
      - apt-get update --yes
      - apt-get -t testing install --yes cmake clang libclang-dev libc6 libgfortran5
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
      - echo "deb http://deb.debian.org/debian experimental main" >> /etc/apt/sources.list
      - echo "deb http://security.debian.org testing main" >> /etc/apt/sources.list
      - apt-get update --yes
      - apt-get -t testing install --yes cmake clang libclang-dev libc6 libgfortran5
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true
