stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
      - cat "deb http://deb.debian.org/debian experimental main" >> /etc/apt/sources.list
      - apt-get update --yes
      - apt-get install --yes cmake clang libclang-dev
      - apt-get -t experimental install libgfortran5
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
      - cat "deb http://deb.debian.org/debian experimental main" >> /etc/apt/sources.list
      - apt-get update --yes
      - apt-get install --yes cmake clang libclang-dev
      - apt-get -t experimental install libgfortran5
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true
