language: rust

before_install:
  - sudo apt-get update --yes
  - sudo apt-get install --yes libopenblas-dev cmake libclang-dev gfortran

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
 
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo
