[package]
name = "ipopt-sys"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.31"
curl = "0.4"
tar = "0.4"
flate2 = "1.0"
