[package]
name = "ipopt-sys"
version = "0.1.1"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
build = "build.rs"
license = "Apache-2.0"
description = "Raw unsafe Rust bindings to the Ipopt non-linear optimization library."
readme = "README.md"

homepage = "https://github.com/elrnv/ipopt-rs"
repository = "https://github.com/elrnv/ipopt-rs"
documentation = "https://docs.rs/ipopt-sys"

keywords = ["non-linear", "optimization", "constrained", "ipopt", "unsafe"]

[build-dependencies]
bindgen = "^0.32"
curl = "0.4"
tar = "0.4"
flate2 = "1.0"
